version: "3.9"

services:
  broker1:
    image: bitnami/kafka:3.7
    container_name: broker1
    hostname: broker1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker1:19092,2@broker2:19092,3@broker3:19092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://broker1:9092,CONTROLLER://broker1:19092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - kafka-net

  broker2:
    image: bitnami/kafka:3.7
    container_name: broker2
    hostname: broker2
    ports:
      - "9093:9092"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker1:19092,2@broker2:19092,3@broker3:19092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://broker2:9092,CONTROLLER://broker2:19092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - kafka-net

  broker3:
    image: bitnami/kafka:3.7
    container_name: broker3
    hostname: broker3
    ports:
      - "9094:9092"
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker1:19092,2@broker2:19092,3@broker3:19092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://broker3:9092,CONTROLLER://broker3:19092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge